### ISSUE TITLE
api for declaring queues and topics programmatically

### ISSUE THREAD

**Issue by tibor-kocsis** [vert-x3/vertx-amqp-bridge#17]
Hi,

currently there is no any api for declaring and configuring queues and topics. If the address is not exists in the broker, it will be an auto created queue, and this is good, but I can't declare any topics in this way. ActiveMQ supports the queue:// and topic:// address prefixes and parses some config from query string, but the others are not. I tried with Jboss AMQ and Apollo Artemis, both of them created an unicast queue, and currently there is no way to pass any configuration programmatically.

Thanks in advance,
Tibor

**Comment by vietj** [comment]
@gemmellr what's your opinion on this ?

**Comment by gemmellr** [comment]
The core AMQP 1.0 spec is primarily about P2P message transfer between named nodes (which might be queues, topics, or something else). It doesn't define a specific broker/server model, or general management operations for creating these nodes.

There is an effort at the OASIS AMQP TC to define a layered management mechanism on top, used by sending AMQP messages, however this is still in draft stages and only a few projects/services support it currently, and not yet in a uniform way. Down the line, this may offer an avenue to provide something in this space, but not currently.

You mentioned Artemis. It offers its own management APIs for creating queues and topics, I'd suggest you look there. Artemis does also support adding a 'queue' or 'topic' capability to the AMQP sender/receiver link target/source terminus to hint whether you want a queue or topic auto-created. However, the bridge has no way to define such detail. You could instead use https://github.com/vert-x3/vertx-proton directly, which can as it exposes far more of the protocol than the bridge can.

I believe you can define the default behaviour for given addresses in Artemis configuration, so you could set things to be auto-created as topics in a given space rather than always queues by default. I vaguely recall seeing mention of configurable queue/topic prefixes as well, in part due to support for older Artemis server/client behaviour where such prefixes were used, perhaps worth asking the Artemis folks. Finally, you can define the specific queues and topics if you already know what they are.

**Comment by tibor-kocsis** [comment]
Thank you for the detailed answer. I prefer using some standardized library to using native drivers, so I will make a try to use vertx-proton to configure the broker. I think this issue should be closed now.
