### ISSUE TITLE
Make AMQP Bridge OSGI Enabled

### ISSUE THREAD

**Issue by yazidaqel** [vert-x3/vertx-amqp-bridge#20]
Make Vertx AMQP Bridge OSGI Enabled
Related Issue: https://github.com/vert-x3/vertx-amqp-bridge/issues/19

**Comment by yazidaqel** [comment]
Should I raise pull request to the master branch instead

**Comment by gemmellr** [comment]
The bridge is being removed in Vert.x 4 so there is nothing on master anymore. The 3.7 branch is likely the only one that might see another release, so any PR should be targeted there.

Given the above, I'd suggest you look at either the new https://github.com/vert-x3/vertx-amqp-client or perhaps  https://github.com/vert-x3/vertx-proton which underpins both it and the bridge.

Ignoring the branch used, PR #21 also isnt acceptable as-is since you reformatted the entire file, including using tabs everywhere instead of spaces. Restore the original formatting so that people can actually see what changed, then match the syntax with any changes/additions you make, which should be the only things shown when viewing a diff.

**Comment by gemmellr** [comment]
@vietj Can you set the default branch to 3.7? I see its set to 3.6.

**Comment by vietj** [comment]
done

**Comment by yazidaqel** [comment]
Thanks for the feedback, pull request has been closed, a new one will be raised with the recommended comments.

**Comment by yazidaqel** [comment]
Closing this item. change has been merged in pull request 20
